### ISSUE TITLE
Missing Trigger Pixel Information

### ISSUE THREAD

**Issue by Superplay64** [MineLittlePony/minelittlepony.github.io#7]
So, this isn't an issue with the mod itself, but rather an issue with information on the mod's usage.  I was about to update the size on an Applebloom skin of mine, when I realized that there seems to be no information about the # color IDs for the new model sizes.  The Race list on the skins page of the website got updated, but the Model Size section did not.  Were these new model sizes removed and not noted, or am I stupidly blind right now and the information is right in front of me?

**Comment by killjoy1221** [comment]
d418f6eae009148c761810adc89d73b2d364defb
